query($owner: String!, $repo: String!, $perPage: Int! $cursor: String) {
  repository(owner: $owner, name: $repo) {
    discussions(first: $perPage, after: $cursor) {
      nodes {
        id
        activeLockReason
        isAnswered
        answer { id }
        answerChosenAt
        answerChosenBy { login }
        author { login }
        authorAssociation
        body
        category { createdAt description emoji id isAnswerable name slug updatedAt }
        comments(first: 100) {
          totalCount
          nodes {
            id
            author { login }
            authorAssociation
            body
            createdAt
            deletedAt
            isMinimized
            minimizedReason
            reactions { totalCount }
            replyTo { id }
            updatedAt
            upvoteCount
            url
          }
        }
        createdAt
        createdViaEmail
        databaseId
        editor { login }
        lastEditedAt
        locked
        number
        publishedAt
        reactions { totalCount }
        title
        updatedAt
        url
      }
	    pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
